### PR TITLE
fixes broken tests / adds lodash to devDeps / refactors package.json …

### PR DESCRIPTION
**Pull request by HenriPodolski**
…template and js dependency handling / adds question for QA and testing tools / prepares for jsLib presets in a separate file

### CODE REVIEW

**Comment by HenriPodolski** [comment]
I guess you have to check out the feature branch to understand the changes. It basically prepares the js stack to have presets, (one question fills in multiple tools for QA and testing)

**Comment by Sebastian-Fitzner** [comment]
I like this approach. Like we discussed on thursday we should separate index.js into sub parts (it is the next step to support a sub generator basis based on a generator file within the generator itself). 

I only changed some minor things: 
- to make it working with our package.json we should only define our generator calls in our setup method (see [fixed setup call order](https://github.com/Prototype-Group/generator-prototype/commit/ea8a4ec8e76d3eed9640056fc9e92629e2247a07))
- indention should be tabs (see [changed structure and indention](https://github.com/Prototype-Group/generator-prototype/commit/0dd995fad5ed0ebdc121e0fb3694ed384d939ddc))
- generator files should be in a separate root folder called `generator-files` so that we could use these in our sub generators, too (see [changed file strucutre](https://github.com/Prototype-Group/generator-prototype/commit/2cd8a44527dff013bad8dc6593e99afd08f775ce)).

Any other ideas or concerns?

**Comment by HenriPodolski** [comment]
Thanks for reviewing and correcting this PR. What about handling the package.json the same way you did with the bower.json? Everything is included and removing what is not needed.

**Comment by Sebastian-Fitzner** [comment]
I also think about that. But do we handle all the grunt/gulp things etc. in this file? 

Furthermore I would like to seperate QA and Testing from JS Libs, because it does not make sense and make it more complex to handle the generation in our package.json ... 
I would like to add a new prompt section with testing questions. 

I pushed a new state which uses the length of the jsLibs object, because the previous version would produce errors when you uncheck jquery in our prompts.

**Comment by HenriPodolski** [comment]
I agree on having an extra question/generator branch for testing related tools and libs.
And I would prefer to handle all stuff that depends on the feature inside this file. Which is the answer to your question:
>  But do we handle all the grunt/gulp things etc. in this file?

**Comment by HenriPodolski** [comment]
I added a working example for the test suite (JSCS with airbnb style preset).

**Pull request merged**
